#Copyright 2024-2026 the original author or authors.
#
#Licensed under the Apache License, Version 2.0 (the "License");
#you may not use this file except in compliance with the License.
#You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
#Unless required by applicable law or agreed to in writing, software
#distributed under the License is distributed on an "AS IS" BASIS,
#WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#See the License for the specific language governing permissions and
#limitations under the License.

FROM eclipse-temurin:17-jre-jammy

WORKDIR /app

COPY data-agent-management/target/*.jar /app/app.jar

RUN apt-get update \
    && apt-get install --no-install-recommends -y python3 \
    && rm -rf /var/lib/apt/lists/* \
    && mkdir -p /app/config

EXPOSE 8065

# 启动命令，优先使用外部配置文件
ENTRYPOINT ["java", "-jar", "/app/app.jar", "--spring.config.location=classpath:application.yml,optional:file:/app/config/application.yml"]
